const TermsConditionsView = () => {
  return (
    <>
      <div className="flex h-[114px] md:h-[272px] flex-col items-center justify-center bg-[#EBF0FA] pt-[15px] md:pt-[0px]">
        <h1 className="text-[20px] md:text-[40px]">Terms and Conditions</h1>
        <p className="text-[14px] md:text-[20px] text-[#565D69]">
          Last updated : 10-Apr-2026
        </p>
      </div>

      <div className="flex flex-col gap-[36px] px-[16px] md:px-[100px] pt-[24px] md:pt-[53px] pb-[84px]">
        <div>
          <h2 className="text-[16px] md:text-[24px] font-[500] mb-[12px]">
            These Terms & Conditions explain how Seil works and what you can
            expect when using the platform. They are written in simple language
            to help you clearly understand your responsibilities and our role.
            <span className="block pt-4 md:pt-5">
              By using Seil, you agree to these terms.
            </span>
          </h2>
        </div>

        <div>
          <h2 className="text-[16px] md:text-[24px] font-[500] mb-[12px]">
            Use of the Platform
          </h2>
          <p className="text-[14px] md:text-[16px]">
            Seil is designed to help users create and manage marketing strategy
            through a guided and structured process. The platform provides
            step-by-step recommendations to support business growth and
            decision-making.
            <span className="block mt-[8px] md:mt-[16px]">
              You agree to use Seil only for lawful and appropriate purposes.
              You must not use the platform in a way that could harm the system,
              interfere with other users, or misuse the tools provided.
            </span>
          </p>
        </div>

        <div>
          <h2 className="font-[500 ] text-[16px] md:text-[24px] mb-[12px]">
            User Responsibilities
          </h2>
          <p className="text-[14px] md:text-[16px]">
            You are responsible for the accuracy of the information you provide
            when using Seil. The results generated by the platform depend on
            your inputs, so providing clear and correct information is
            important.
            <span className="block mt-[8px] md:mt-[16px]">
              You are also responsible for how you apply the strategies and
              recommendations provided. Seil does not control your actions
              outside the platform and cannot guarantee how results will turn
              out.
            </span>
          </p>
        </div>
        <div>
          <h2 className="text-[16px] md:text-[24px] font-[500] mb-[12px]">
            Generated Content
          </h2>
          <p className="text-[14px] md:text-[16px]">
            Seil generates marketing strategy, tasks, and recommendations based
            on your responses. These are designed to guide your decision-making
            and help you take action.
            <span className="block mt-[8px] md:mt-[16px]">
              However, these outputs are suggestions and not guaranteed
              outcomes. Business results may vary depending on how the
              strategies are implemented and other external factors.
            </span>
          </p>
        </div>
        <div>
          <h2 className="text-[16px] md:text-[24px] font-[500] mb-[12px]">
            Account & Access
          </h2>
          <p className="text-[14px] md:text-[16px]">
            If you create an account on Seil, you are responsible for
            maintaining the security of your login details. You should not share
            your account information with others.
            <span className="block mt-[8px] md:mt-[16px]">
              We reserve the right to suspend or restrict access if we detect
              misuse, suspicious activity, or actions that violate these terms.
            </span>
          </p>
        </div>
        <div>
          <h2 className="text-[16px] md:text-[24px] font-[500] mb-[12px]">
            Limitation of Liability
          </h2>
          <p className="text-[14px] md:text-[16px]">
            Seil is provided as a support tool to guide your marketing efforts.
            While we aim to provide helpful and accurate recommendations, we do
            not guarantee specific results.
            <span className="block mt-[8px] md:mt-[16px]">
              We are not responsible for any losses, damages, or business
              outcomes that may occur from using the platform or relying on its
              recommendations.
            </span>
          </p>
        </div>
        <div>
          <h2 className="text-[16px] md:text-[24px] font-[500] mb-[12px]">
            Changes to the Terms
          </h2>
          <p className="text-[14px] md:text-[16px]">
            We may update these Terms & Conditions from time to time to reflect
            changes in the platform or improvements to our services.
            <span className="block mt-[8px] md:mt-[16px]">
              When significant updates are made, we will make reasonable efforts
              to inform users so they are aware of the changes.
            </span>
          </p>
        </div>
      </div>
    </>
  );
};

export default TermsConditionsView;
